#' Convert an object of class MRInput from the MendelianRandomization package to the RadialMR rmr_format class
#'
#' Creates a data.frame with class `rmr_format` from an object of class `MRInput` generated by [`MendelianRandomization::mr_input`].
#'
#' @param dat Object from [`MendelianRandomization::mr_input`].
#'
#' @export
#' @return Object of class `rmr_format`, the RadialMR format
#' @examples
#' if (require("MendelianRandomization", quietly = TRUE)) {
#' dat <- data_radial[data_radial[,10] < 5e-8,]
#' dat <- MendelianRandomization::mr_input(bx = dat$ldlcbeta,
#'                                         bxse = dat$ldlcse,
#'                                         by = dat$chdbeta,
#'                                         byse = dat$chdse,
#'                                         snps = dat$rsid)
#' dat <- mrinput_to_rmr_format(dat)
#' head(dat)
#' class(dat)
#' }
mrinput_to_rmr_format <- function(dat) {
  if (!("MRInput" %in% class(dat))) {
    stop('The class of the input data object must be "MRInput"')
  }

  out <- format_radial(BXG = dat@betaX,
                       BYG = dat@betaY,
                       seBXG = dat@betaXse,
                       seBYG = dat@betaYse,
                       RSID = dat@snps)
  out
}
